name: Build and push

on:
  pull_request:
    types: [closed]
    branches: master

env:
  FULL_IMAGE_NAME: gazprom-neft/ds-py3

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: docker build build -t ${{ env.FULL_IMAGE_NAME }}

    - name: Push
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push ${{ env.FULL_IMAGE_NAME }}
